env:
  global:
    - secure: u5v54so3qH1ApjounDvcrPmLZt+eSeHi7xs/hMVVsr7x3anlh3YpfckuaVgxjT5VPcr1cxPS+gbSkuk3bs9rWTISLJo5IQz8VOfLzOgK1ZNRr+n5ZELXY+/PqLUniP9v3PAtgch7XNCKCn9s3Vh9knSh+VzfDysdDHWLYm4pOunf/lPnZ+Mee5DkclQk/qHMKJcNSRBzPxN2duzhp+xRSZk/Y5M0lH1Dc7TIQNU8yyYmX1kgal3nBVi0G2Z9vlrHahIcyUQYY8eBdIHt+jDSdvb1/H29Nw2R5PoEJsNC7i626rVwZHGryikbe9Fv9oaJ/J/FXeD/XM6qNEzBG+AGL/J0307LThYEtNOhsKL0jC+Uhopvah3mhSXsC9isKgg7Ec9675F7SF52LwqyQrAyXgK7ejadKD+eS48JtUwKk0aL3oXeofW3N+Yu8liueYkKweBw6idWdr2AndZeTDU3cXi+MhZ38S2sge2rq+c4BWpuvji4CL4oeLmw0ECc1NrAIO2MPGEq/iJUx6BlWQ+4lamQ3FtigGGlFDnQXEINDcfJYzlU4NEjzQ8mgLamEp79fgXO6mE5eJ0Q1JNJgSfQh/5Y0/uB797KhO0NYf/vtEMw2PYOq3YQGpkFhoO90ZmGVO6tW6nWO26ZqQ2PTOMCu3uI4fzo643SDJzdbbAW0AU=
    - secure: XxF4gWYwfMOLgrcU0OzIHv6W4c/pfXWeWVmQGnan+bfhsTSAE2BgX+Ba2Q785HV5F41KuiKO/j+BLPfwB8QUJxVp8lYLb1IHkJAKRa5JmBlHBs6pczf7UcMU/wPYGD+JFp4v1hYgo39GXFuYkgIWwOagKJD928BLuza7OnVzqELqmijtL6E1TMB0/PnpytfXB9D3zok08gzi9CpXr6cLa8AUGreYNS0/It6M0bmTBVfc1VthE/fSKkUatyCsvZxbN+KC2oMH3OT353eyVUjwWKpkRpO2OGtXivHWupmKxRE9x3ya/GWsLsVgdSR0N6xLwjlUP0DmwqFdfrIDWPFLpHLy5wd01ZssFUZOorzRpigBWVE0VVgDOJ7lut0GLKfWI4y0/lQjIVyHiPe3dr0hhghJU9pElctpqiKuvLs971nrQxIKjNrgO1cfYQe1FPsDG5G+H5b+l0LDZ2lQ2+YWs1j+JgTV0MX9DwnM9wXtnYeYK5MhTYd95L8LDHJWkjituSrMKKcf81wqGOqUt5QsPB7Cg59eZclKb67OPWQg9yosO5yYNpEtbDwC00bEKqAN9WKxyvU7smEORQOghYCH85eGBPYZ88njTMB7S+bYdlf8CH4AFpNgyblrJusyCars7ONAafjGZH/0MGfsR/zkHd3jMF6X5XfpFVaoOyyFiC8=
    - secure: hX9h8YgOE0FGlcCixl7sPo7ELCdkLiGI/zgXYxbOADDwRENzYRkvqwjmHW5sV7VmxJTnZ29s8Q7Xhf52MH7o72OhmBhxswxTNMsq9OV54u4bWezfWwSFxB3zpc9C7sREBxOV6lHgyTrZuo2URyibQqtaAJWrNfAT4qayWT+bi1S3v9iYyBQlzTyGaWJjc6zS9KSROEPtMpAC4XhThqa6dHXOR9SOMjSEpi57EEZCw1ZlXSrRxzOJqJj5r8cAb84H3xZ66/6ByBWxOzxPQmV95j3p8caLjYPiqQsqha9070yT9NcJ1c/KWIQxALcToNGOwLwQXUpVaUz5c5OGrdqbg0ch2OX7RgsN6w9XOVkijDlSifCeZZSkUbwY1FrFKd41b2IWA6T6yzW6sWa3prxdDCKBKnmVOn1Cp9Rc/pvJYWQ9Asw58utHvFOsfi4MJqkspaEdk+kcunh+8WkZ2ri5VV051VuKsVFdZGR3+gspuhrIcd5ommFZCBp1Bu69xLi1UOAfrNpussxuikSDeK94cWfGCULWSqcY5V7rMxhcklCaHBOoIu6jx57qvsy4fV8yCvTHX0jba1z1jQuuepzyTrUGiQ3UfjzxgDW71IQ5foLQNS1bXh7CvHt9dq8e2UtS09yaUcrNezPb7wOFp5OoQgGkZLH8PWAx60313QJziEU=
    - secure: OPwduJFkdLaLWZkgfxuIgLY2CwpFd7Fgs1CT2mZiZxkdJ8t6KQvDnIvgbXcIabzb8feYqD9zHi4lFOtjtSpYwAJ24bQ3hT4KbA+TL1k1DHdtTbwxGOdOuU2P2oIBWHWULvfKuFGVp9OiKI+1q1UqW1SdVEvih/3JUuKh1bK0BceqbXTKtZxIcoq+YBEIAeqbMlNoHf6Y4FyxM513lgqszjhfpVUDfykBVTaMDzbkbm9OWXEun4jP6a/vEFFkJEgB3YtsBGD98HRKTkM7Vhr7hfCmWhpuPNZaPG2DBu/pJvC/qz9NZrquaBjGpuA/GK2zE+UcYm5vzsgoAxa1soHp1laxDhU+S/hBowxQUoailZBzMPdfr4XL9+QwZHb4sDwU7n/WUUt2ouptf5geqMnGiZfJcmjJ8M+WXlxNe6j/ji5DMbJGYhT11pUNAYXsSnntb02vAYYndKNvJtQCmf6JbA1zsNSS3E4sQP5F42wkVDV/+tbbKYS76HFSVZyEWPsRjDK/Kr5NiZJCKYpv5iVivmGMuMNQa5rziV7t+I0Z+sM9bA2klEQ1BF/oHwA+1vG2NPYQ84FxSxywurmZwAgyLNKV2FfMjRoM/I8m7Bv3FYCvq5bYTaAMTsmwltNmyf9ntiYcSc9Dc3kOa72w1uRQxFdAvW6h38I6Qlht0E/zAMQ=
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
before_deploy: cd build; zip -r build.zip .
service:
  - docker
deploy:
- provider: releases
  api_key:
    secure: DxPVJQZcVbn/uLx3qOk4eKmB/10BabM3sG6schxKxHr53un7J1/V0QFxmlXVCg7Xf8cGEkzs+UETgc4i3GL0lZtS/DQ5xpfwJNUZ3+XfymQ0x7OsDiaK83/ohKBH3j0R+qbUESzlY2F2FSfMQxhj9Fv7Xkg6bZaiURrq7MHmbDJQtW1hXI3W3+8Ye9rXnveenITK5wo/N2idUu+oJeat3Lk5NBtCbE7AkXSws2OC9Za/Rll33lS/8lKoVSzxRyvOaPLy2z4004OL1ZgHzxmr73HNd4amkkvyCBTU66f9X/n6DV+tV5OiFbW0mn37DCTuVgNAex8bPecOZFvjWuALwjRfT5nqTwzbZ1AWux3MisOC2QuTPoBqo+AhA0kgeVFdQwkLhfkCtVDOJYuXNd1+/3VjO55MA/mynbC3tvAiPEu2Hg3xtb+TAkZXyIleWilZvgIGrAVT8ZNWkP6zABQVAc20sbyV6KNEi1eCHZSUWitB6IRHbT8F7dpYcgPzbvLUKiCTftXyilnb28/awNUVuXMfOKy28U2b8+Py3yNgrXj3a7Hkv+pRcHH8KU/fSdzOF54Cm6pCXBO1O7BidfKSIBwF4Oq/OW7JnpfxhPaF8oTQ3EIt1rAoA8/UPoE5ozz4hv38e88/J7kK/Zc3Ani/6WWTBZAaF0t5g3pXOMDcHmg=
  file: build.zip
  skip_cleanup: true
  on:
    repo: Bob-MusicPlayer/front-bob
    all_branches: true
after_success:
- env
- echo ${DOCKER_USERNAME}
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t ${REPO}:${COMMIT} .
- docker tag ${REPO}:${COMMIT} ${REPO}:${TAG}
- docker tag ${REPO}:${COMMIT} ${REPO}:travis-${TRAVIS_BUILD_NUMBER}
- docker push ${REPO}
